-- log(serpent.block(data.raw["ambient-sound"]))

-- Remove default songs
-- data.raw["ambient-sound"] = {}

-- Add songs
data:extend{{
    name = "sc-01-opening",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/sc-01-opening.ogg",
},{
    name = "sc-02-under-construction",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/sc-02-under-construction.ogg",
},{
    name = "sc-04-some-elements",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 3,
    sound = "__more-music__/music/sc-04-some-elements.ogg",
},{
    name = "sc-05-discovery",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 3,
    sound = "__more-music__/music/sc-05-discovery.ogg",
},{
    -- Regular version
    name = "sc-07-new-world",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/sc-07-new-world.ogg",
},{
    -- Menu track
    name = "sc-07-new-world-menu",
    type = "ambient-sound",
    track_type = "menu-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/sc-07-new-world.ogg",
},{
    name = "sc-08-some-calm",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/sc-08-some-calm.ogg",
},{
    name = "sc-10-working",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 3,
    sound = "__more-music__/music/sc-10-working.ogg",
},{
    name = "sc-11-finale",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/sc-11-finale.ogg",
},{
    name = "pz-long-ambient",
    type = "ambient-sound",
    track_type = "interlude",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-long-ambient.ogg",
},{
    name = "oldtorio-01-intro",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 4,
    sound = "__more-music__/music/oldtorio-01-intro.ogg",
},{
    name = "oldtorio-02-haluzsqua",
    type = "ambient-sound",
    track_type = "interlude",
    planet = "nauvis",
    weight = 4,
    sound = "__more-music__/music/oldtorio-02-haluzsqua.ogg",
},{
    name = "oldtorio-03-sepro1",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 4,
    sound = "__more-music__/music/oldtorio-03-sepro1.ogg",
},{
    name = "pz-they-were-once-here",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-they-were-once-here.ogg",
},{
    name = "pz-barricading",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-barricading.ogg",
},{
    name = "pz-maybe-not",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-maybe-not.ogg",
},{
    name = "pz-misc",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-misc.ogg",
},{
    name = "pz-guitar",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-guitar.ogg",
},{
    name = "pz-what-was-lost",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-what-was-lost.ogg",
},{
    name = "pz-raider",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-raider.ogg",
},{
    name = "pz-wwl-active",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-wwl-active.ogg",
},{
    name = "pz-work_fast",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 3,
    sound = "__more-music__/music/pz-work-fast.ogg",
},{
    name = "pz-the_inevitable",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 2,
    sound = "__more-music__/music/pz-the-inevitable.ogg",
},{
    name = "pz-wwl_tense",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 3,
    sound = "__more-music__/music/pz-wwl-tense.ogg",
},{
    name = "ftl-01-Title-Screen",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-01-Title-Screen.ogg",
},{
    name = "ftl-02-Milkyway-Explore",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-02-Milkyway-Explore.ogg",
},{
    name = "ftl-03-Civil-Explore",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-03-Civil-Explore.ogg",
},{
    name = "ftl-07-Mantis-Explore",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-07-Mantis-Explore.ogg",
},{
    name = "ftl-08-Engi-Explore",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-08-Engi-Explore.ogg",
},{
    name = "ftl-11-Rockmen-Explore",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-11-Rockmen-Explore.ogg",
},{
    name = "ftl-13-Zoltan-Explore",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-13-Zoltan-Explore.ogg",
},{
    name = "ftl-15-Milkywa-Battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-15-Milkywa-Battle.ogg",
},{
    name = "ftl-16-Civil-Battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-16-Civil-Battle.ogg",
},{
    name = "ftl-17-Cosmos-Battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-17-Cosmos-Battle.ogg",
},{
    name = "ftl-21-Engi-Battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-21-Engi-Battle.ogg",
},{
    name = "ftl-22-colonail-battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-22-colonail-battle.ogg",
},{
    name = "ftl-24-rockmen-battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-24-rockmen-battle.ogg",
},{
    name = "ftl-26-zoltan-battle",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-26-zoltan-battle.ogg",
},{
    name = "ftl-27-last-stand-platform",
    type = "ambient-sound",
    track_type = "main-track",
    planet = "nauvis",
    weight = 1,
    sound = "__more-music__/music/ftl-27-last-stand-platform.ogg",
}}
